Ubisoft/Controllers/AcercaDeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Ubisoft.Controllers
{
    public class AcercaDeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ubisoft/Controllers/LoginController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ubisoft.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Ubisoft.Controllers
{
    namespace Ubisoft.Controllers
    {
        public class LoginController : BaseController
        {
            public LoginController(UbisoftContext context) : base(context) { }
            // GET: /<controller>/        
            public IActionResult Index()
            {
                return View();
            }
            [HttpPost]
            [ValidateAntiForgeryToken]
            public IActionResult Index(Persona persona)
            {

                if (ModelState.IsValid)
                {
                    var personita = from p in Context.Personas
                                    where p.Username.Equals(persona.Username) && p.Contraseña.Equals(persona.Contraseña)
                                    select p;
                    var test = personita.ToList().FirstOrDefault();
                    if (test == null)
                    {
                        ViewBag.error = "Datos ingresado de manera erronea o no registrado :c";
                        return View();
                    }

                    return View("Index", test);
                }

                return View();
            }
        }
    }

}

Ubisoft/Controllers/TiendaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ubisoft.Models;
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Ubisoft.Controllers
{
    public class TiendaController : BaseController
    {
        public TiendaController(UbisoftContext context) : base(context) { }
        public IActionResult Index()//Linkear una consulta de muchos a muchos 
        {
            var productos = Context.ProductoConCaracteristicas;
            //Se tiene que modificar el contexto para cargar datos de manera diligente
            Context.Caractersisticas.Include(b => b.ProductoConCaracteristicas).ToList();
            Context.Productos.Include(b => b.ProductoConCaracteristicas).ToList().GetRange(2, 3);

            var query = from feature in productos
                        group feature by feature.Producto into detalles
                        select detalles;
            return View(query);
        }
    }
}

Ubisoft/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ubisoft</title>
    <link rel="stylesheet" href="~/css/site.min.css" />  
</head>
<body>    
    <header>
        <nav class="negro">
            <a asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/logo.png" alt="LOGO" /></a>
            <ul>                
                <li><a asp-area="" asp-controller="Tienda" asp-action="Index">Tienda</a></li>
                <li><a asp-area="" asp-controller="AcercaDe" asp-action="Index">Acerca de</a></li>
                <li><a asp-area="" asp-controller="Login" asp-action="Index">Login</a></li>
            </ul>            
        </nav>
    </header>
    

    <partial name="_CookieConsentPartial" />    
        @RenderBody()  
        <footer>
            <small>&copy; 2019 Ubisoft.com - Todos los derechos reservados</small>
        </footer>
       
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    
    
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>   

    @RenderSection("Scripts", required: false)
</body>
</html>